from pptx import Presentation
from pptx.util import Pt


def add_bullet_slide(prs, title, content):

    slide = prs.slides.add_slide(prs.slide_layouts[1])

    slide.shapes.title.text = title

    content_box = slide.placeholders[1]
    text_frame = content_box.text_frame
    text_frame.clear()

    sentences = content.split(". ")

    # only 5 bullets per slide
    for i, sentence in enumerate(sentences[:5]):

        if i == 0:
            p = text_frame.paragraphs[0]
        else:
            p = text_frame.add_paragraph()

        # keep bullet short
        p.text = sentence[:80]
        p.level = 0
        p.font.size = Pt(18)


def create_ppt(topic, report):

    prs = Presentation()

    # Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = topic.title()

    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = (
            "Generated by Autonomous Research Agent"
        )

    # Split report
    chunks = [
        ("Introduction", report[:800]),
        ("Key Findings", report[800:1600]),
        ("Benefits", report[1600:2400]),
        ("Challenges", report[2400:3200]),
        ("Future Scope", report[3200:4000]),
        ("Conclusion", report[4000:4800]),
    ]

    for title, content in chunks:
        add_bullet_slide(prs, title, content)

    # Thank You Slide
    slide = prs.slides.add_slide(prs.slide_layouts[5])

    slide.shapes.title.text = "AI Architecture"

    slide.shapes.add_picture(
        "images/image_1.jpg",
        1,
        1,
        width=4000000
)

    prs.save("report.pptx")

    return "report.pptx"